### ISSUE TITLE
kernel.asm: replace `cli` with `sti` to get interrupts working

### ISSUE THREAD

**Issue by rizet** [AVCADO/avcOS#3]
I noticed you were working on interrupts and I noticed `kernel.asm` performs a `cli` before calling `kmain`. You might want to replace that with `sti`, so then you can test your interrupt functionality.

**Comment by AVCADO** [comment]
It's working but it triple faults if you don't have `cli` somewhere so I did this
```x86asm
...
sti
call kmain
cli
...
```
which does not triple fault
